[package]
name = "dlr"
version = "0.1.0"
authors = ["saeed.m <saeed.moqadam@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
pbr = "*"
clap="*"
regex="*"
url="*"
percent-encoding="*"
serde_urlencoded = "0.5.5"
serde_derive = "1.0.94"
serde = { version = "1.0", features = ["derive"] }
